const express=require('express'); const cors=require('cors'); const crypto=require('crypto'); const Razorpay=require('razorpay'); require('dotenv').config();
const app=express(); app.use(cors({origin:process.env.CLIENT_URL||true})); app.use(express.json());
const products=[{id:'p1',ownerId:'o1',name:'Canon EOS Camera',description:'Professional camera for events and travel.',category:'Electronics',mode:'both',salePrice:85000,dailyPrice:1200,weeklyPrice:7000,deposit:10000,location:'Mumbai',image:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=900'}];
const bookings=[];
function days(a,b){const x=new Date(a),y=new Date(b); return Math.max(0,Math.ceil((y-x)/86400000));}
function quote(p,start,end){const d=days(start,end); if(!d) throw Error('End date must be after start date'); const base=d>=7?Math.floor(d/7)*p.weeklyPrice+(d%7)*p.dailyPrice:d*p.dailyPrice; return {days:d,rental:base,deposit:p.deposit,subtotal:base+p.deposit,total:base+p.deposit};}
app.get('/api/health',(req,res)=>res.json({ok:true})); app.get('/api/products',(req,res)=>res.json(products));
app.get('/api/products/:id',(req,res)=>{const p=products.find(x=>x.id===req.params.id); p?res.json(p):res.status(404).json({error:'Not found'})});
app.post('/api/products',(req,res)=>{const p={id:'p'+(products.length+1),ownerId:'demo-owner',...req.body}; products.push(p); res.status(201).json(p)});
app.post('/api/bookings/quote',(req,res)=>{try{const p=products.find(x=>x.id===req.body.productId); if(!p) return res.status(404).json({error:'Product not found'}); res.json(quote(p,req.body.startDate,req.body.endDate));}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/bookings',(req,res)=>{try{const p=products.find(x=>x.id===req.body.productId); if(!p) return res.status(404).json({error:'Product not found'}); const q=quote(p,req.body.startDate,req.body.endDate); const overlap=bookings.some(b=>b.productId===p.id && new Date(req.body.startDate)<new Date(b.endDate) && new Date(req.body.endDate)>new Date(b.startDate)); if(overlap)return res.status(409).json({error:'Dates unavailable'}); const b={id:'b'+(bookings.length+1),...req.body,...q,status:'pending'}; bookings.push(b); res.status(201).json(b)}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/payments/razorpay/order',async(req,res)=>{if(process.env.PAYMENT_MODE==='mock')return res.json({mode:'mock',orderId:'mock_'+Date.now(),amount:req.body.amount}); try{const r=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET}); const order=await r.orders.create({amount:Math.round(req.body.amount*100),currency:'INR',receipt:req.body.bookingId}); res.json({mode:'razorpay',keyId:process.env.RAZORPAY_KEY_ID,order});}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/payments/razorpay/verify',(req,res)=>{const {orderId,paymentId,signature}=req.body; const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET||'').update(orderId+'|'+paymentId).digest('hex'); if(process.env.PAYMENT_MODE!=='mock'&&expected!==signature)return res.status(400).json({error:'Invalid signature'}); const b=bookings.find(x=>x.id===req.body.bookingId); if(b)b.status='paid'; res.json({verified:true})});
app.listen(process.env.PORT||4000,()=>console.log('API on '+(process.env.PORT||4000)));
